#!/usr/bin/env python

import sys
import re
import subprocess
filen = sys.argv[-1]
exename = "./enzo.exe"


with open(filen,'r') as f:
    for line in f.readlines():
        match = re.match('^BT symbol: (.+ )?\[(0x[0-9a-f]+)\]', line)
        #cmd = ['addr2line']
        cmd = ['atos']
        if match:
            cmd.append("-e %s" % exename)
            cmd.append("-i %s" % match.group(2))
            subprocess.call(' '.join(cmd), shell=True)

#end
