#! /bin/tcsh

# CheckForDifferences: differences two code versions
# args: 
#  v: after each file, prints the line count of diff
#  v v: writes the diff out
# d1 = src
# d2 = whatever's in the file ./dir

set d1 = "src"

#diff args
set DA = "-wc"

#if( $1 == "" || $1 == "v" || $1 == "c") then
#    set d2 = "../"`cat dir`
#else
#    set d2 = "../"$1
#endif

# Better ways to find the 

cd $1
set d1 = `pwd`
cd -
cd $2
set d2 = `pwd`
cd -

# hack:
#set d1 = '0501_Good'
#set d2 = '0501_StillDivLessSegFaults'
#

echo $d1 " " $d2 

cd $d1 

set NewFiles = 0
set NewLinesThisFile = 0
set NewLinesNewFiles = 0
set NewLinesOldFiles = 0
set AllNewLines = 0

#set files = " *.C *.h *.src "
set files = " *.C *.src *.h"
#set files = " * "
foreach i ( $files )

    if(  -e $d2/$i ) then
	if( `diff -w $i $d2/$i |wc -l` != 0 ) then 

	    if( $1 == "v" && $2 == "v" ) then 
		    echo "ooo"
		    diff $i $d2/$i
	    endif
	    if( $1 == "v" ) then
		    diff $i $d2/$i |wc -l
	    endif

	    set Lines1 = `wc -l $i | awk '{print $1}' `
	    set Lines2 = `wc -l $d2/$i | awk '{print $1}' `
	    @ NewLinesOldFiles = $NewLinesOldFiles + $Lines1 - $Lines2
	    @ NewLinesThisFile = $Lines1 - $Lines2
	    echo $i $NewLinesThisFile $NewLinesOldFiles
	    
	endif
    else
	echo XXXXXXXXXXXXXX $d2/$i doesnt exist
	@ NewLinesNewFiles = $NewLinesNewFiles + `wc -l $i | awk '{print $1}'`
	@ NewFiles = $NewFiles + 1
	echo $NewLinesNewFiles
    endif
end

    echo New Lines, New Files = $NewLinesNewFiles
    echo New Files            = $NewFiles
    echo New Lines, Old Files = $NewLinesOldFiles
    @ AllNewLines = $NewLinesNewFiles + $NewLinesOldFiles
    echo new Lines, Total     = $AllNewLines

cd $d2

foreach i ( $files )

    if( ! (-e $d1/$i) ) then

	echo YYYYYYYYYYYYYY $d1/$i doesnt exist

    endif

end

#end
