#!/bin/csh -f
#
# A sed script for moving # to the beginning of the line.
#

echo $1

sed -e "s/\(^[[:space:]][[:space:]]*\)#/#\1/" $1 > tmp
mv tmp $1
#       :::                           ::  :::
#           