#!/bin/tcsh
if( $machine == mustang ) then
    set scr = Script.mustang
else
    set scr = Script.lobo
endif
grep "set Dir" $scr
sed -i "s,set Dir = .*,set Dir = `pwd`", $scr
grep "set Dir" $scr
#end
