#!/bin/tcsh -f


foreach i (`dirlist`)
	echo "cd " $i
	cd $i
	dirpurge
	cd ..
	set kill = `dirlist`
#	set kill = `find . -type d -empty`
	if( "$kill" != "" ) rmdir $kill
#	echo "k: " `find . -empty`

end

#
