#!/bin/tcsh
if( $1 == "" ) then
    echo "dpm <joblog>"
    echo "Parses output.  Moves job records around."
    echo "If job has completed, moves output to Meta dir"
    exit
endif
set JobScript = ""
if( $2 != "" ) then
    set JobScript = $2
endif
if ( 0 == 0 ) then
set jobid = `echo $1 | cut -c 7- | cut -d . -f -1`
set filename = $1
if ( ! -e $filename ) then
    echo "dpm: no such file " $filename
    exit
endif
set still_running = True
if( `dstat |grep $jobid` == "" ) then
    set still_running = False
endif
DaveParse.py $filename
if( $still_running == True ) then
    echo "vim $filename"
    echo "Job still running"
else
    ddel $jobid 1
    if( ! -e Meta ) mkdir Meta
    mv $filename Meta
    echo "vim Meta/$filename"
    echo "job finished."
endif
endif
if ( $JobScript != "" ) then
    setenv LastID  `dsub $JobScript 1`
    echo "Submitted Job" $JobScript
    if ( ! -e LastID ) touch LastID
    echo $LastID >> LastID
    echo Submitted $JobScript $LastID 
endif
#end
