#!/bin/tcsh
set echo
set quiet = No
if ( "$1" == "-q" ) then
    set quiet = Yes
endif
if ( $quiet == "No" ) then
    dstat 
endif
source $ScriptDir/DOTdschedrc
switch( $machine )
    case "lobo":
    case "mapache":
    case "conejo":
    case "mustang":
        set still_running = `dstat |grep david_c |awk '{print $1}'`
        breaksw
    case "arronax":
    case "natilus":
    case "conseil":
    case "kraken":
        set still_running = `dstat |grep collins | cut -f -1 -d "." `
        breaksw
endsw
foreach i ($still_running)
    grep $i $AllRuns
end

#end
