#!/bin/tcsh
set duud = duud
while( $#argv )
    switch( $1 )
    case "-n":
        shift
        set duud = $1
        shift
        breaksw
    case "-d":
        shift
        set mydir = $1
        shift
        breaksw
    endsw
end
if( -e $duud ) rm $duud
if( -e $duud.sort) rm $duud.sort
if( `uname` == Darwin ) then 
  du -h -d 1 > $duud
else
  du -h --max-depth=1 > $duud
endif

if ( $?mydir ) then
    awk '{print $1 "  '$mydir'/"$2}' $duud > tmp_90210
    mv tmp_90210 $duud
endif

SortDU $duud
cat $duud.sort
ls $duud $duud.sort
#end
