#!/bin/tcsh
echo $argv
if ( $#argv > 0 ) then
  set duud = $1
else
  set duud = duud
endif

if( -e $duud ) rm $duud
if( -e $duud.sort) rm $duud.sort
if( `uname` == Darwin ) then 
  du -h -d 1 > $duud
else
  du -h --max-depth=1 > $duud
endif


SortDU $duud
cat $duud.sort
ls $duud $duud.sort
#end
