#!/bin/tcsh

set rev = ""
if ( $1 == "-r" ) then
    set rev = "-r $2"
    shift
    shift
endif

foreach i ($argv ) 
    cp -i $i $i.back
    git checkout $rev $i
end

#end
#while( $#argv )
#    switch( $1 )
#    case "0":
#    set nProcCompile = ""
#    shift
#    breaksw
