#!/bin/ksh

# Select the location where you are running this script
# X="gsiftp://hpss.sdsc.edu:2811"
# X="gsiftp://ds-gridftp.sdsc.edu:2811"
# X="gsiftp://tg-gridftp.sdsc.teragrid.org:2811"
# X="gsiftp://gridftp-abe.ncsa.teragrid.org:2811"
# X="gsiftp://gridftp-co.ncsa.teragrid.org:2811"
# X="gsiftp://tg-gridftp.ncsa.teragrid.org:2811"
X="gsiftp://gridftp.nics.teragrid.org:2811"
# X="gsiftp://gridftp1.ranger.tacc.utexas.edu:2811"
# X="gsiftp://tg-gridftp.lonestar.tacc.teragrid.org:2811"

Y=`pwd`
Z=`basename ${2}`
Z="/"${Z}

B=${2}
C=

GUC="globus-url-copy"

case $1 in

# Copy from SDSC HPSS

       ds-hpss )
       A="gsiftp://hpss.sdsc.edu:2811/users/sdsc/harkness/"
       BS="1048576"
       SBS="268787456"
       STR="-stripe"
       PRO="8"
       echo "Copy "${A}${B}${C}
       echo "To   "${X}${Y}${Z}
       $GUC -vb $STR -p $PRO -sbs $SBS -tcp-bs $BS ${A}${B}${C} ${X}${Y}${Z}
       ;;

# Copy from SDSC Datastar /dsgpfs

       ds-work )
       A="gsiftp://ds-gridftp.sdsc.edu:2811/dsgpfs/harkness/"
       BS="1048576"
       SBS="268787456"
       STR="-stripe"
       PRO="12"
       echo "Copy "${A}${B}${C}
       echo "To   "${X}${Y}${Z}
       $GUC -vb $STR -p $PRO -sbs $SBS -tcp-bs $BS ${A}${B}${C} ${X}${Y}${Z}
       ;;

       ds-sac )
       A="gsiftp://ds-gridftp.sdsc.edu:2811/dsgpfs/projects/SAC/harkness/"
       BS="1048576"
       SBS="268787456"
       STR="-stripe"
       PRO="12"
       echo "Copy "${A}${B}${C}
       echo "To   "${X}${Y}${Z}
       $GUC -vb $STR -p $PRO -sbs $SBS -tcp-bs $BS ${A}${B}${C} ${X}${Y}${Z}
       ;;


       ds-enzo )
       A="gsiftp://ds-gridftp.sdsc.edu:2811/dsgpfs/projects/enzo/harkness/"
       BS="1048576"
       SBS="268787456"
       STR="-stripe"
       PRO="12"
       echo "Copy "${A}${B}${C}
       echo "To   "${X}${Y}${Z}
       $GUC -vb $STR -p $PRO -sbs $SBS -tcp-bs $BS ${A}${B}${C} ${X}${Y}${Z}
       ;;

# Copy from SDSC Teragrid /gpfs

       tg-work )
       A="gsiftp://tg-gridftp.sdsc.teragrid.org:2811/gpfs/harkness/"
       BS="1048576"
       SBS="268787456"
       STR="-stripe"
       PRO="12"
       echo "Copy "${A}${B}${C}
       echo "To   "${X}${Y}${Z}
       $GUC -vb $STR -p $PRO -sbs $SBS -tcp-bs $BS ${A}${B}${C} ${X}${Y}${Z}
       ;;

       tg-sac )
       A="gsiftp://tg-gridftp.sdsc.teragrid.org:2811/gpfs/projects/SAC/harkness/"
       BS="1048576"
       SBS="268787456"
       STR="-stripe"
       PRO="12"
       echo "Copy "${A}${B}${C}
       echo "To   "${X}${Y}${Z}
       $GUC -vb $STR -p $PRO -sbs $SBS -tcp-bs $BS ${A}${B}${C} ${X}${Y}${Z}
       ;;

       tg-enzo )
       A="gsiftp://tg-gridftp.sdsc.teragrid.org:2811/gpfs/projects/enzo/harkness/"
       BS="1048576"
       SBS="268787456"
       STR="-stripe"
       PRO="12"
       echo "Copy "${A}${B}${C}
       echo "To   "${X}${Y}${Z}
       $GUC -vb $STR -p $PRO -sbs $SBS -tcp-bs $BS ${A}${B}${C} ${X}${Y}${Z}
       ;;

# Copy from SDSC BlueGene /bggpfs

       bg-work )
       A="gsiftp://bg-gridftp.sdsc.edu:2811/bggpfs/harkness/"
       BS="1048576"
       SBS="268787456"
       STR="-stripe"
       PRO="12"
       echo "Copy "${A}${B}${C}
       echo "To   "${X}${Y}${Z}
       $GUC -vb $STR -p $PRO -sbs $SBS -tcp-bs $BS ${A}${B}${C} ${X}${Y}${Z}
       ;;

       bg-sac )
       A="gsiftp://bg-gridftp.sdsc.edu:2811/bggpfs/projects/SAC/harkness/"
       BS="1048576"
       SBS="268787456"
       STR="-stripe"
       PRO="12"
       echo "Copy "${A}${B}${C}
       echo "To   "${X}${Y}${Z}
       $GUC -vb $STR -p $PRO -sbs $SBS -tcp-bs $BS ${A}${B}${C} ${X}${Y}${Z}
       ;;

# Copy from NCSA Mercury /gpfs_scratch1

       hg-work )
       A="gsiftp://tg-gridftp.ncsa.teragrid.org:2811/gpfs_scratch1/harkness/"
       BS="1048576"
       SBS="268787456"
       STR="-stripe"
       PRO="12"
       echo "Copy "${A}${B}${C}
       echo "To   "${X}${Y}${Z}
       $GUC -vb $STR -p $PRO -sbs $SBS -tcp-bs $BS ${A}${B}${C} ${X}${Y}${Z}
       ;;

# Copy from NCSA Cobalt /scratch/users

       co-work )
       A="gsiftp://gridftp-co.ncsa.teragrid.org:2811/scratch/users/harkness/"
       BS="1048576"
       SBS="268787456"
       STR="-stripe"
       PRO="12"
       echo "Copy "${A}${B}${C}
       echo "To   "${X}${Y}${Z}
       $GUC -vb $STR -p $PRO -sbs $SBS -tcp-bs $BS ${A}${B}${C} ${X}${Y}${Z}
       ;;

# Copy from NCSA Abe /cfs/scratch/users

       abe-work )
       A="gsiftp://gridftp-abe.ncsa.teragrid.org:2811/cfs/scratch/users/dcollins/"
       BS="1048576"
       SBS="268787456"
       STR="-stripe"
       PRO="12"
       echo "Copy "${A}${B}${C}
       echo "To   "${X}${Y}${Z}
       $GUC -vb $STR -p $PRO -sbs $SBS -tcp-bs $BS ${A}${B}${C} ${X}${Y}${Z}
       ;;

# Copy from TACC Lonestar /work/staff

       ls-work )
       A="gsiftp://tg-gridftp.lonestar.tacc.teragrid.org:2811/work/staff/harkness/"
       BS="1048576"
       SBS="268787456"
       STR="-stripe"
       PRO="12"
       echo "Copy "${A}${B}${C}
       echo "To   "${X}${Y}${Z}
       $GUC -vb -tcp-bs $BS ${A}${B}${C} ${X}${Y}${Z}
       ;;

# Copy from TACC Ranger /scratch/00770

       tx-work )
       A="gsiftp://gridftp1.ranger.tacc.utexas.edu:2811/scratch/00369/tg456484"
       BS="1048576"
       SBS="268787456"
       STR="-stripe"
       PRO="12"
       echo "Copy "${A}${B}${C}
       echo "To   "${X}${Y}${Z}
       echo $GUC -vb $STR -p $PRO -sbs $SBS -tcp-bs $BS ${A}${B}${C} ${X}${Y}${Z}
       $GUC -vb $STR -p $PRO -sbs $SBS -tcp-bs $BS ${A}${B}${C} ${X}${Y}${Z}
       ;;

# Copy from PSC BigBen /scratcha

       bb-work )
       A="gsiftp://tg-gridftp.bigben.psc.teragrid.org:2811/scratcha/harkness/"
       BS="1048576"
       SBS="268787456"
       STR="-stripe"
       PRO="12"
       echo "Copy "${A}${B}${C}
       echo "To   "${X}${Y}${Z}
       $GUC -vb $STR -p $PRO -sbs $SBS -tcp-bs $BS ${A}${B}${C} ${X}${Y}${Z}
       ;;

# Copy from NICS Kraken /lustre/scratch

       kr-work )
       A="gsiftp://gridftp1.nics.teragrid.org:2811/lustre/scratch/collins/"
       BS="1048576"
       SBS="268787456"
       STR="-stripe"
       PRO="12"
       echo "Copy "${A}${B}${C}
       echo "To   "${X}${Y}${Z}
       $GUC -vb $STR -p $PRO -sbs $SBS -tcp-bs $BS ${A}${B}${C} ${X}${Y}${Z}
       ;;

# Copy from SDSC GPFS-WAN

       wan-work )
       A="gsiftp://tg-gridftp.sdsc.teragrid.org:2811/gpfs-wan/scratch/harkness/"
       BS="1048576"
       SBS="268787456"
       STR="-stripe"
       PRO="12"
       echo "Copy "${A}${B}${C}
       echo "To   "${X}${Y}${Z}
       $GUC -vb $STR -p $PRO -sbs $SBS -tcp-bs $BS ${A}${B}${C} ${X}${Y}${Z}
       ;;

       wan-asta )
       A="gsiftp://tg-gridftp.sdsc.teragrid.org:2811/gpfs-wan/projects/asta/harkness/"
       BS="1048576"
       SBS="268787456"
       STR="-stripe"
       PRO="12"
       echo "Copy "${A}${B}${C}
       echo "To   "${X}${Y}${Z}
       $GUC -vb $STR -p $PRO -sbs $SBS -tcp-bs $BS ${A}${B}${C} ${X}${Y}${Z}
       ;;

       wan-enzo )
       A="gsiftp://tg-gridftp.sdsc.teragrid.org:2811/gpfs-wan/projects/lca/harkness/"
       BS="1048576"
       SBS="268787456"
       STR="-stripe"
       PRO="12"
       echo "Copy "${A}${B}${C}
       echo "To   "${X}${Y}${Z}
       $GUC -vb $STR -p $PRO -sbs $SBS -tcp-bs $BS ${A}${B}${C} ${X}${Y}${Z}
       ;;

# failure
       * )
       ;;

esac


