#!/bin/tcsh
set f1 = $1
set f2 = $2
if( -e $f2.hdiff ) rm $f2.hdiff
if( -e $f1.hdiff ) rm $f1.hdiff
egrep -v "FieldType|Task|BaryonFileName" $f1 > $f1.hdiff
egrep -v "FieldType|Task|BaryonFileName" $f2 > $f2.hdiff
vimdiff $f1.hdiff $f2.hdiff

#end
