#!/bin/tcsh
touch mantra
echo "mantra" >> mantra
set total = 0
if ( $1 != "" ) then
    set total = $1
endif
set n = 0
while ( 1 )
@ n = $n + 1
echo $n
set dest = $cloudbreak/data/cb1/dccollins/Paper19/p19_newscripts/plots_to_sort/
scp mantra $dest
rsync -avz --remove-source-files -e ssh $dest"*" .
#rsync -avz --remove-source-files -e ssh $nazare./PigPen/"*" .
if (  $n > $total ) then
    break
else

sleep 5
end
if ( -e mantra ) rm mantra
#end
