#!/bin/tcsh
if ( $1 == "" ) then 
    echo ">lnk image"
    echo "prints an html anchor with image link"
else
    foreach i ($argv)
	echo '<a href = '$i'><img src = '$i' width = 400></a><br>'
    end
endif   

#end
