#!/bin/tcsh

if( $#argv < 2)then
echo 'foreach i (`nums $1 $2`)'
echo 'DD$i/data$i `grep InitialTime data$i |awk {print $3}`'
exit
endif
if( $3 == "" || $3 == "old") then
foreach i (`nums $1 $2`)
echo DD$i/data$i `grep InitialTime data$i |awk '{print $3}'`
end
endif
if( $3 == "DD" ) then
 foreach i (`nums $1 $2`)
 echo DD$i/data$i `grep InitialTime DD$i/data$i |awk '{print $3}'`
 end

endif

#end
