#!/usr/bin/env python


import sys
import os
from optparse import OptionParser

def GetRelativeRoot():
    cwd =os.getcwd().split('/')
    output = './'
    nWorks =  cwd.count('Work')
    foundIt = 0
    for i in range(len(cwd)-1,0,-1):
        if cwd[i] == 'Work':# and cwd[i-1] == 'Research':
            foundIt = 1
            nWorks = nWorks - 1        
        else:
            if nWorks > 0:
                output = output + "../"
    if foundIt == 0:
        return "./"
    else:
        return output


parser = OptionParser()
parser.add_option("-c","--color", dest="color", action="store_true",default=False,
                  help="Color options css")
parser.add_option("-t","--table", dest="tablemaker", action="store_true",default=False,
                  help="Headder and suggestion for tablemaker")
(options, args) = parser.parse_args()

if len(args)  != 1:
    print 'newhtml filename <opts>'
    print 'makes new html file.'
    print 'newhtml --help for help'
else:

    RelativeRoot = GetRelativeRoot()

    filename = args[0]

    if filename.split('.')[-1] != "html":
        filename = filename + ".html"
    if os.path.exists(filename):
        print "File",filename,"exists.  Move it."
        sys.exit(0)
    file = open(filename,'w')

    file.write('<html>\n<head>\n')
    if options.color:
        file.write('<link rel="stylesheet" href="'+
                   RelativeRoot+'Colors.css" typ="text/css" media=screen>\n')
    if options.tablemaker:
        file.write('<script language="JavaScript" type="text/javascript" src = "'+
                   RelativeRoot+'tablemaker.js"></script>\n')
        file.write('<script language="JavaScript" type="text/javascript" src = "'+
                   RelativeRoot+'sorttable.js"></script>\n')
    file.write('</head>\n')
    file.write('<body>\n')
    file.write('<h1></h1>\n')
    if options.tablemaker:
        file.write('<!--- sample for tablemaker --->\n'+
                   '<script language="JavaScript" type="text/javascript">\n'+
                   'var Runs = new Array();\n'+
                   'Runs.push({\n'+
                   '"thing":"text"});\n'+
                   'tablemaker(Runs);\n'+
                   '</script>\n')

    file.write('</body>\n')
    file.write('</html>\n')
    file.close()

#end
