#!/bin/tcsh
set echo
if ( $#argv == 0 ) then
    echo "nget3 var"
    echo "gets *var* form nazare, opens *var*"
else
    if ( $#argv == 2 ) then
        scp $nazare./yt3_scripts/"*$1*$2" .
        open *"$1"*"$2"
    else
        scp $nazare./yt3_scripts/"*$1*" .
        open *"$1"*
    endif
endif
#end
