#!/bin/tcsh
set echo
set yt_dest = $HOME/local-yt-2014-01-01
source $yt_dest/bin/activate.csh
set compile = 0
if ( $#argv > 0 ) then
    set compile = 1
endif

if ( $compile ) then
    cd ../src/enzo
    make clean
    make -j 8;
    if ( ! $status ) then
        echo "Compile Failed"
        exit 1
    endif
    cd -
endif

set name = "_E28_enzo-dev"
set loc = /scratch1/dcollins/TestRunner/dev
set todo =  --suite=quick 
set todo = "$todo --answer-store "
set goldname = _gold_2015-07-31
set logname = runner_log.`date +"%Y-%m-%d-%H-%M-%S"`

echo test_runner.py --run-suffix=$name -o $loc $todo --local --local-dir=$loc   --answer-name=$goldname >& $logname
test_runner.py --run-suffix=$name -o $loc $todo --local --local-dir=$loc   --answer-name=$goldname |& tee -a $logname


#end
