#!/bin/tcsh
set echo
set Name = $1
WN $Name
shift
if( "$1" == "-w") then
    set args = "common ms write make figs herp"
else if ("$1" == "-y" ) then
    set args = "yt2 src lookit herp"
else if ("$1" == "-y2" ) then
    set args = "yt1 yt2 src lookit herp scratch1 scratch2"
else if ("$1" == "-run" ) then
    set args = "yt src lookit herp ed1 ed2 run1 run2"
else if ("$1" == "-x" ) then
    set args = "other hw1 hw2 hwOld eqn1 eqn2 plt1 plt2 python"
else if ("$1" == "-9" ) then
    set args = "R1 e1 l1 R2 e2 l2 R3 e3 l3"
else
    set args = ($argv)
endif
touch $HOME/screen_loc
uname -n >> $HOME/screen_loc
set tmp_exec = '/var/tmp/screenm_tmp'
if( -e $tmp_exec ) rm $tmp_exec
touch $tmp_exec
echo '#\!/bin/tcsh' >> $tmp_exec
echo 'set echo' >> $tmp_exec
echo 'foreach i ('$args')'>> $tmp_exec
echo 'screen -t  $i '>> $tmp_exec
echo 'end'  >> $tmp_exec
chmod a+x $tmp_exec
ll $tmp_exec
screen -S $Name $tmp_exec
#if( -e $tmp_exec ) rm $tmp_exec
#end
