#!/bin/tcsh

#cat things |sed -n 's:\(ux454321\):&:p'
#cat things |sed -n 's:\(kywong\):&:p'
showq |/opt/freeware/bin/sed -n 's:\(ux454321\)\|\(ACTIVE JOBS\)\|\(IDLE JOBS\)\|\(NON-QUEUED JOBS\)\|\(JOBNAME\):&:p'

#end
