#!/bin/tcsh
#CVS crap
setenv CVSROOT ":pserver:dcollins@lca2.ucsd.edu:/usr/local/mhd"
setenv CVS_RSH ssh
setenv EDITOR vim
set EDITOR = vim
setenv CVSEDITOR vim
setenv backups "*~ *#* .#*"
setenv a "*.C *.h *.src *.f *.F"

#
# Machine Overloads
#

set tgN = "dcollins@tg-login.ncsa.teragrid.org:"
set tgS = "ux454321@tg-login.sdsc.teragrid.org:"
set CO = "dcollins@cobalt.ncsa.teragrid.org:"
set kraken = "collins@kraken.nics.utk.edu:"
set krakenp = "collins@kraken-pwd.nics.utk.edu:"
set ds = "ux454321@dslogin.sdsc.edu:"
set dsdirect = "ux454321@dsdirect.sdsc.edu:"
set abe = "dcollins@abe.ncsa.uiuc.edu:"
set pp = "dcollins@ppcluster.ucsd.edu:"
set lca2 = "dcollins@lca2.ucsd.edu:"
set ranger="tg456484@tg-login.ranger.tacc.teragrid.org:"
set rangerw="tg456484@tg-login.ranger.tacc.teragrid.org:/scratch/00369/tg456484/"
set triton="dccollin@triton-login.sdsc.edu:"
set subsonic="dcollins@69.254.149.103:"
set yellow="david_c@yr-fe1"
set nautilus="collins@login.nautilus.nics.teragrid.org:"
set noclobber

#
# HG repo variables
#
set woc_repo = "http://dcollins:se7meaor@hg.spacepope.org/week-of-code/"
set mrg_repo = "http://dcollins:se7meaor@hg.spacepope.org/mhdctmerge/"


#
# Things that I've disabled, and may break other things.
#
#if python 2.4.x isn't the default, set python24 in .cshrc
#if ( ! ( -e ~/Scripts/python24 ) ) ln -s /usr/bin/python ~/Scripts/python24

#set path=($path ~/Scripts . $src)
#echo "warning: path not set correctly.  totalview wont' work."
set path=($path ~/Scripts . )



#
# Determine machine, for preferences and prompts.
#


#set prompt_word = $machine	
set prompt_word = "%m"
if( $?machine == 0 ) then
    #for the mac: It's the only darwin, and the '-a' option output changes with location.
    if( `uname` == Darwin ) then 
        set machine = MAC
        set prompt_word = MAC
        alias gsed /sw/bin/sed
    else
        set machine = `uname -a | awk '{print $2}'`
    endif



    #triton
    if( $machine == login-4-0.local ) then
       set prompt_word = "triton"
    endif
else
    set prompt_word = $machine
endif

#teragrid sub-nodes
if( `echo $machine | cut -c 1-4` == tg-c ) then
    set prompt_word = "TG"
endif

#cobalt
if( `echo $machine | cut -c 1-8` == co-login ) then
    set prompt_word = "CO"
endif

#abe
if( `echo $machine | cut -c 1-6` == honest ) then
    set prompt_word = "ABE"
endif

#cluster
if( `echo $machine | cut -c 1-9` == ppcluster ) then
    set prompt_word = "PP"
endif

#helsinki
if(`hostname` == "naiad.astro.helsinki.fi" ) set prompt_word = NAIAD
if(`hostname` == "hectar.astro.helsinki.fi" ) set prompt_word = HECTAR
if( `hostname |cut -c 1-3` == sky ) set prompt_word = `hostname |cut -c 1-4`
    


#Teragrids need a little more love.
if ( `echo $machine |cut -c 1-8` == "tg-login" ) then
   if( `hostname -f |cut -d . -f 2` == sdsc ) then
	set prompt_word = "tgS"
	unset machine
	setenv machine  tgS
	#printf "\033]2;tgS\007"
   endif
   if( `hostname -f |cut -d . -f 2` == ncsa ) then
	 set prompt_word = "tgN"
	unset machine
	 setenv machine tgN
	# printf "\033]2;tgN\007"
   endif
        
endif

#
# Just to be sure...
#
setenv machine $machine
if( `hostname | cut -f 2 -d .` == ranger) then
    set prompt_word = "RANGER"
endif

alias prompt_long set prompt = $prompt_word":%~\>"
alias prompt_short set prompt = $prompt_word":%c\>"
alias prompt_shortest set prompt = "%c\>"
prompt_long
#
# Aliases for directories.
#
alias calc 'awk "BEGIN{ print \!* }" ' 

alias mhdctmerge "echo no mhdctmerge directory defined."
if( $?mhdctmerge != 0 ) then 
alias mhdctmerge "cd $mhdctmerge" 
endif

alias mhd "echo no mhd directory defined."
if( $?mhd != 0 ) then 
alias mhd "cd $mhd" 
endif
alias devel "echo no devel directory defined."
if( $?devel != 0 ) then
 alias devel "cd $devel"
 endif

alias llnl "echo no llnl directory defined."
if( $?llnl != 0 ) then
 alias llnl "cd $llnl"
endif

alias scratch "echo no scratch directory defined."
if( $?scratch != 0 ) then
 alias scratch "cd $scratch"
endif

alias src "echo no src directory defined."
if( $?src != 0 ) then
 alias src "cd $src"
 endif

alias src2 "echo no src2 directory defined."
if( $?src2 != 0 ) then
 alias src2 "cd $src2"
 endif

alias stable "echo no stable directory defined."
if( $?stable != 0 ) then
 alias stable "cd $stable"
 endif

alias unstable "echo no unstable directory defined."
if( $?unstable != 0 ) then
 alias unstable "cd $unstable"
 endif

alias wan "echo no wan directory defined."
if( $?wan != 0 ) then
 alias wan "cd $wan"
 endif

alias trunk "echo no trunk directory defined."
if( $?trunk != 0 ) then
 alias trunk "cd $trunk"
 endif
alias woc "echo no woc directory defined."
if( $?woc != 0 ) then 
alias woc "cd $woc"
endif

alias yoc "echo no yoc directory defined."
if( $?yoc != 0 ) then
  alias yoc "cd $yoc"
endif

if( $?mrg != 0 ) then
    alias mrg "cd $mrg"

    if( -e $mrg/merge_tools )then
     set path=($path $mrg/merge_tools )
    endif

else
    alias mrg "echo No mrg dir defined."
endif

#
# Because I can't type
#

if(  $machine != MAC ) alias make gmake
alias moer         'more'
alias mroe         'more'
alias meor         'more'

alias more less
#
# Because Im Lazy
#

alias li "ls -1 |grep -i \!*"
alias ll ls -l
alias la ls -a
alias lh ls -lh
alias emacs "emacs -nw"
alias em "emacs \!*"

alias cvd "cvs diff -wc \!* |less"
alias svd "svn diff \!* |less"
alias hgd "hg diff \!* |less"
alias hgs "hg status \!* |less"
alias cvu "cvs update"
alias svd "svn diff \!* |less"

alias gko "gdsm kr \!* -o"
alias gk  "gdsm kr \!*"
alias gto "gdsm triton \!* -o"
alias gt "gdsm triton \!*"
#
# batch queries
#

alias dstat "qstat -u `whoami`"

#
# Experiments.
#

alias AliasCmdLineArgs "echo Your command line args are \!*"
alias name       'printf "\033]0;\!*\007"'


alias perf '/usr/local/apps/perf/perf \!*'

alias ack '~/Scripts/ack --nogroup \!*'

#if ( ${?SSH_TTY} ) then
#    echo "dont forget to check the code back in"
#endif

#
# To make other scripts more general
# This is actually breaking with the general paradigm of this
# script, namely checking existance of things set in .cshrc.  
#

switch( $machine )
    case "lca2.ucsd.edu":
        set open_png = feh
        set open_pdf = acro
        breaksw
    case "MAC":
        set open_png = open
        set open_pdf = open
        breaksw

endsw
