#!/usr/bin/env python

import os
import sys

# make sure the cadac classes are in our path
scriptfile = os.path.abspath(sys.argv[0])
scriptdir = os.path.dirname(scriptfile)
packagedir = os.path.dirname(scriptdir)
sys.path.append(packagedir)

from cadac import client

username = sys.argv[1]
password = sys.argv[2]
run_file = sys.argv[3]

add_loc = '/xml/members/'

fin = open(run_file)
xml = fin.read()
fin.close()

# 0 is good, otherwise -HTTP response code.
post_status, new_id = client.post(username, password, add_loc, xml)

post_status *= -1

sys.exit(post_status)

